apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: kube-rbac-proxy
          args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          ports:
          - containerPort: 8443
            name: https
        - name: manager
          image: stanfordoval/almond-cloud:latest
          imagePullPolicy: IfNotPresent
          command:
          - /usr/local/bin/backend
          args:
          - manager
          - --namespace=tba
          # - --aws-tls-cert=/etc/aws/aws-global-bundle.pem
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          env:
          - name: ENABLE_INTEGRATION
            value: "true"
          - name: INTEGRATION_ARGS
            value: "manager --namespace=default --health-probe-bind-address=:8081 --metrics-bind-address=127.0.0.1:8080 --leader-elect"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
            requests:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
          - mountPath: /etc/almond-cloud/config.d/config.yaml
            name: config
            readOnly: true
            subPath: config.yaml
          - mountPath: /etc/almond-cloud/config.d/secret.yaml
            name: secret
            readOnly: true
            subPath: secret.yaml
          - mountPath: /etc/almond-cloud/manager-config
            name: manager-config
          # - mountPath: /etc/aws
          #   name: aws-secret
          #   readOnly: true
      securityContext:
        fsGroup: 65534
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: almond-config
      - name: secret
        secret:
          secretName: almond-secret
      - name: manager-config
        configMap:
          name: manager-config
      # - name: aws-secret
      #   secret:
      #     secretName: aws-tls-secret
